# Generated by Django 6.0.8 on 2026-10-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='handled',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes. These are not shown to the customer.'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('completed', 'Completed'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.CharField(choices=[('Cybersecurity', 'Cybersecurity'), ('Networking', 'Networking'), ('IoT / Smart Home', 'IoT / Smart Home'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Electrical Engineering', 'Electrical Engineering'), ('Training', 'Training'), ('Consulting', 'Consulting'), ('Other', 'Other')], max_length=120),
        ),
    ]
